version: '3'
services:
  srvchecker:
   build:
    context: .
    dockerfile: schDockerfileOpt
   image: wihiss/srvchkr:v1
   restart: always
   volumes:
    - /home/eugene/Projects/DotNetCore/srvchkrdata:/srvchkr/ServicesChecker/data
    - /home/eugene/Projects/DotNetCore/ServicesChecker/ServicesChecker/bin/Debug/config:/srvchkr/ServicesChecker/config
    - /home/eugene/Projects/DotNetCore/srvchkrdata:/srvchkr/ServicesChecker/logs
  srvcheckerwa:
   build:
    context: .
    dockerfile: waDockerfileOpt
   image: wihiss/srvchkrwa:v1
   restart: always
   ports:
    - "5000:80"
   volumes:
    - /home/eugene/Projects/DotNetCore/srvchkrdata:/srvchkr/ServiceCheckerWebApp/data
    - /home/eugene/Projects/DotNetCore/ServicesChecker/ServiceCheckerWebApp/bin/Debug/config:/srvchkr/ServiceCheckerWebApp/config
   depends_on:
    - "srvchecker"
