services:
 - id: 1
   name: Test
   host: testsrv
   port: 9430
   period: 10
   disabled: false

output:
   outputType: MongoDb
   target: localhost
   port: 5515
   dbName: srvChkrDb
   tableName: output
   user:
   password:
