services:
 - id: 1
   name: Test
   host: testsrv
   port: 9430
   period: 10
   disabled: false
 - id: 2
   name: DM.COM
   host: http://depechemode.com
   period: 30
   disabled: false

output:
   storageType: File
   address: D:\Projects\DotNetCore\ServiceCheckerData

#historyLoader:
#   storageType: File
#   address: d:\
