services:
 - id: 1
   name: Test
   host: testsrv
   port: 9430
   period: 10
   disabled: false

output:
   storageType: MongoDb
   address: localhost
   port: 5515
   dbName: srvChkrDb
   tableName: output
   user:
   password:

historyLoader:
   storageType: MongoDb
   address: localhost
   port: 5515
   dbName: srvChkrDb
   tableName: output
   user:
   password: